### ISSUE TITLE
HungerStrike: Possible incompatibility

### ISSUE THREAD

**Issue by Vazkii** [jaquadro/ForgeMods#1]
It seems like having HungerStrike enabled leaves the Lexica Botania from Botania in a state where it can't be opened, removing HS fixes the issue. Here's the code for it:
https://github.com/Vazkii/Botania/blob/master/MODSRC/vazkii/botania/common/item/ItemLexicon.java#L53

Mod List (with forge 1048):
![](http://puu.sh/7SbdB.png)

**Comment by jaquadro** [comment]
Could you verify whether this is a problem with 1.7.2.0 or not?

**Comment by jaquadro** [comment]
I was able to reproduce the problem (on both 1.7.2.0 and 1.7.2.1).  I'll look a bit more to see if I can see a cause for the conflict.

**Comment by jaquadro** [comment]
Release hs-1.7.2.2 should solve this problem.  It was related to how the server/client side was checked when hunger strike was enabled.  The problem would not surface until hunger strike was turned on for a player, but then the only way to correct it would be restarting the server.
